### ISSUE TITLE
Error: Cannot find module 'react-docgen/dist/babylon' (v1)

### ISSUE THREAD

**Issue by mrmos** [doczjs/docz#822]
## Bug Report

**Describe the bug**

Docz fails to build when you have an `include` or `exclude` path in your .babelrc file. For example:

**babel.config.js**
```javascript
module.exports = {
  exclude: 'node_modules/**',
  presets: ['@babel/preset-react', ['@babel/preset-env', { targets: { node: 'current' } }]],
  plugins: ['@babel/plugin-proposal-class-properties', '@babel/plugin-proposal-object-rest-spread'],
}
```

This worked in previous versions of Docz, but fails after upgrading to v1

**Comment by fi3ework** [comment]
Could you provide a minimal reproduce repo? Thanks!

**Comment by mrmos** [comment]
Without that property, build works fine. With it, I cannot `dev` or `build` the project successfully, as the error mentioned in the title is thrown.

**Comment by zicodeng** [comment]
Related: https://github.com/pedronauck/docz/issues/727
